version: '3'

services:
  backend:
    env_file:
      "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "backend:be"